# Generated by Django 3.2.4 on 2021-06-05 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='description',
            new_name='audio',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='title',
            new_name='options',
        ),
    ]
