# Generated by Django 3.2.4 on 2021-06-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20210605_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='audio',
            field=models.FileField(blank=True, upload_to='audio'),
        ),
    ]
