# Generated by Django 3.2.4 on 2021-06-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_todo_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='todo',
            name='options',
        ),
        migrations.AddField(
            model_name='todo',
            name='options',
            field=models.ManyToManyField(to='todos.Option'),
        ),
    ]
